### ISSUE TITLE
Claim of more efficientcy lacks evidence

### ISSUE THREAD

**Issue by marcoscaceres** [w3ctag/packaging-on-the-web#2]
The document sez:

> Delivering a package of these files could be more efficient than delivering individual files. Downloading each file has a connection overhead which is particularly impactful on low-bandwidth mobile devices and on secure connections.

This claim needs clarification, data, and citations. Particularly, what is the impact for a common website over HTTP? What would it be over HTTP2? what could it theoretically be over using packaging? 

I know people have done the research for HTTP and HTTP2 - but probably not for the kind of packaging being suggested by this document.

**Comment by ryankshaw** [comment]
Indeed, In the readme it says "[spdy/http2] do not enable the server to deliver content for predicted requests", that is not true. SPDY/HTTP 2.0 have both server push (http://www.igvita.com/2013/06/12/innovating-with-http-2.0-server-push/) and server hint (http://www.chromium.org/spdy/link-headers-and-server-hint). I don't get what these packages buy us over that. in both cases, you'd need tooling to figure out all of the things that need to go into your 'package'. With push, rather than building an archive and creating an entirely new specification/workflow around understanding that archive, you just send an extra header. the other benefit of relying on spdy/http2 is that you can control caching on a more granular level. if one little gif or one js file changes, you dont need to invalidate the entire archive, just that one file.

It seems like allowing people to combine the benefits of:
1. spdy/http2 server push/hints
2. serviceWorkers
3. server/build-time tooling 

would allow people to do anything you could do with these packages and would be more of a "extensible web" thing to do. this seems somewhat "app-cach"ey (as in, "we know exactly what you want and here's the grand scheme of how you're going to do it" as opposed to "here are a bunch of primitives that give you what you need, combine them together to build what you want"). Maybe I am missing something though, is there something fundamentally that one of these packages could do that those 3 could not?

**Comment by JeniT** [comment]
I've tried to tackle these issues in the newly written draft specification at http://w3ctag.github.io/packaging-on-the-web, in particular indicating that packaging isn't a magic performance silver bullet and that it can be over used. I've also tried to make the point that packages can work in concert with HTTP/2 or SPDY, and tried to demonstrate the unique advantages that packages have in areas other than performance. I'm open to more challenges about the claims, but I don't think they're particularly strong now.

**Comment by ryanflorence** [comment]
@JeniT 

> I'm open to more challenges about the claims, but I don't think they're particularly strong now.

Which claims? Because if you mean the claims of packages being more efficient then I don't think this issue should be closed.

If you mean the claims that @ryankshaw made, then I'd expect a better response than what you've supplied.
